/**
 * Secure Copy Screen Tests
 * 
 * Tests the secure copy screen including:
 * - Loading and formatting emergency plan data
 * - Copying plan to clipboard
 * - Navigation to main screen
 * - Loading states
 * - Error handling
 * - Plan text formatting
 */

import React from "react";
import { render, fireEvent, waitFor, act } from "@testing-library/react-native";
import SecureCopy from "../secure-copy";
import * as Sentry from "@sentry/react-native";

// Mock expo-router
const mockPush = jest.fn();
const mockReplace = jest.fn();

jest.mock("expo-router", () => ({
  useRouter: () => ({
    push: mockPush,
    replace: mockReplace,
  }),
  Stack: {
    Screen: ({ children, options }: any) => children,
  },
}));

// Mock Clipboard - must be before the component import
const mockSetString = jest.fn();

jest.mock("react-native/Libraries/Components/Clipboard/Clipboard", () => ({
  default: {
    setString: mockSetString,
  },
  setString: mockSetString,
}));

// Mock Sentry
jest.mock("@sentry/react-native", () => ({
  captureException: jest.fn(),
}));

// Mock app settings
jest.mock("../../../utils/app-settings", () => ({
  useAppSettings: () => ({
    settings: {
      language: "en",
    },
  }),
}));

// Mock translations
jest.mock("../../../translations", () => ({
  usePageTranslation: () => ({
    t: (key: string) => {
      const translations: Record<string, string> = {
        header: "Secure Copy",
        title: "Save a Copy of Your Plan",
        recommendation: "We recommend saving a copy of your emergency plan in a secure location.",
        instructionsTitle: "Instructions:",
        step1: "Copy your plan below",
        step2: "Open your Notes app or another secure location",
        step3: "Paste and save your plan",
        step4: "Store it somewhere you can access quickly",
        yourPlan: "Your Emergency Plan",
        loading: "Loading...",
        copyPlan: "Copy to Clipboard",
        copied: "Copied!",
        shareInstructions: "You can share this with trusted contacts or save it for your records.",
        continue: "Continue",
        skip: "Skip",
        planIntroMessage: "Hi, I'd like you to have a copy of my Emergency Plan (below), which I have prepared in case I am detained. I am safe now. You do not need to do anything beyond keeping this message as a record…",
        myEmergencyPlan: "MY EMERGENCY PLAN",
        message: "Message",
        messageContent: "Message Content",
        contacts: "Contacts",
        noContacts: "No contacts added",
        generatedBy: "Generated by",
        keepSafe: "Keep this information safe and secure.",
        noPlanData: "No emergency plan data found.",
        errorLoadingPlan: "Error loading your emergency plan.",
      };
      return translations[key] || key;
    },
  }),
}));

// Mock storage utils
const mockLoadEmergencyPlanData = jest.fn();

jest.mock("../../../utils/storage-utils", () => ({
  loadEmergencyPlanData: () => mockLoadEmergencyPlanData(),
}));

// Mock Button
jest.mock("../../../components/Button", () => {
  return jest.fn((props) => {
    const React = require("react");
    const { TouchableOpacity, Text } = require("react-native");
    return React.createElement(
      TouchableOpacity,
      {
        testID: `button-${props.text.toLowerCase()}`,
        onPress: props.onPress,
      },
      React.createElement(Text, null, props.text)
    );
  });
});

// Mock EmergencyPlanBottomNavigation
jest.mock("../../../components/EmergencyPlanBottomNavigation", () => {
  return jest.fn(() => {
    const React = require("react");
    const { View } = require("react-native");
    return React.createElement(View, { testID: "bottom-navigation" });
  });
});

// Mock Ionicons
jest.mock("@expo/vector-icons", () => ({
  Ionicons: () => null,
}));

describe("SecureCopy Screen", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    jest.useFakeTimers();
    
    // Reset clipboard mock
    mockSetString.mockClear();
    
    // Default mock - return empty messages
    mockLoadEmergencyPlanData.mockResolvedValue({ messages: [] });
  });

  afterEach(() => {
    act(() => {
      jest.runOnlyPendingTimers();
    });
    jest.useRealTimers();
  });

  describe("Rendering", () => {
    it("renders the screen with title", async () => {
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Save a Copy of Your Plan")).toBeTruthy();
      });
    });

    it("renders instructions", async () => {
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Instructions:")).toBeTruthy();
        expect(getByText("Copy your plan below")).toBeTruthy();
        expect(getByText("Open your Notes app or another secure location")).toBeTruthy();
        expect(getByText("Paste and save your plan")).toBeTruthy();
        expect(getByText("Store it somewhere you can access quickly")).toBeTruthy();
      });
    });

    it("renders continue and skip buttons", async () => {
      const { getByTestId } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByTestId("button-continue")).toBeTruthy();
        expect(getByTestId("button-skip")).toBeTruthy();
      });
    });

    it("renders copy button", async () => {
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
    });

    it("shows loading state initially", () => {
      const { getByText } = render(<SecureCopy />);
      
      expect(getByText("Loading...")).toBeTruthy();
    });

    it("hides loading state after data loads", async () => {
      const { queryByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(queryByText("Loading...")).toBeNull();
      });
    });
  });

  describe("Loading Emergency Plan Data", () => {
    it("loads emergency plan data on mount", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "I need legal help",
            contacts: [],
          },
        ],
      });
      
      render(<SecureCopy />);
      
      await waitFor(() => {
        expect(mockLoadEmergencyPlanData).toHaveBeenCalled();
      });
    });

    it("displays formatted plan text", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "I need legal help",
            contacts: [
              { id: "1", name: "John Doe", phoneNumber: "5551234567" },
            ],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/I'd like you to have a copy of my Emergency Plan/)).toBeTruthy();
        expect(getByText(/Message 1: Legal Support/)).toBeTruthy();
        expect(getByText(/I need legal help/)).toBeTruthy();
      });
    });

    it("handles empty messages array", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({ messages: [] });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("No emergency plan data found.")).toBeTruthy();
      });
    });

    it("handles load error", async () => {
      mockLoadEmergencyPlanData.mockRejectedValue(new Error("Load failed"));
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Error loading your emergency plan.")).toBeTruthy();
        expect(Sentry.captureException).toHaveBeenCalled();
      });
    });
  });

  describe("Plan Formatting", () => {
    it("formats plan with message topic and content", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Work Absences",
            message: "I will not be at work today",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/Message 1: Work Absences/)).toBeTruthy();
        expect(getByText(/I will not be at work today/)).toBeTruthy();
      });
    });

    it("formats plan with contact information", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "Help needed",
            contacts: [
              { id: "1", name: "Jane Doe", phoneNumber: "5559876543" },
              { id: "2", name: "John Smith", phoneNumber: "5551234567" },
            ],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/Jane Doe - 5559876543/)).toBeTruthy();
        expect(getByText(/John Smith - 5551234567/)).toBeTruthy();
      });
    });

    it('shows "No contacts" when contacts array is empty', async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Other",
            message: "Test message",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/No contacts added/)).toBeTruthy();
      });
    });

    it("formats multiple messages correctly", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "Legal help needed",
            contacts: [],
          },
          {
            id: "2",
            topic: "Pet Care",
            message: "Please feed my dog",
            contacts: [{ id: "1", name: "Neighbor", phoneNumber: "5551111111" }],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/Message 1: Legal Support/)).toBeTruthy();
        expect(getByText(/Message 2: Pet Care/)).toBeTruthy();
        expect(getByText(/Legal help needed/)).toBeTruthy();
        expect(getByText(/Please feed my dog/)).toBeTruthy();
      });
    });

    it('includes "Generated by ReadyNow" footer', async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Other",
            message: "Test",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/Generated by ReadyNow/)).toBeTruthy();
        expect(getByText(/Keep this information safe and secure/)).toBeTruthy();
      });
    });
  });

  describe("Copy to Clipboard", () => {
    it("copies plan to clipboard when copy button is pressed", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "I need help",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
      
      const copyButton = getByText("Copy to Clipboard");
      fireEvent.press(copyButton);
      
      expect(mockSetString).toHaveBeenCalledWith(
        expect.stringContaining("I'd like you to have a copy of my Emergency Plan")
      );
    });

    it('shows "Copied!" after copying', async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "Test",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
      
      const copyButton = getByText("Copy to Clipboard");
      fireEvent.press(copyButton);
      
      await waitFor(() => {
        expect(getByText("Copied!")).toBeTruthy();
      });
    });

    it('resets to "Copy to Clipboard" after 3 seconds', async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "Test",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
      
      const copyButton = getByText("Copy to Clipboard");
      fireEvent.press(copyButton);
      
      await waitFor(() => {
        expect(getByText("Copied!")).toBeTruthy();
      });
      
      // Fast-forward 3 seconds
      act(() => {
        jest.advanceTimersByTime(3000);
      });
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
    });

    it("copies complete formatted plan", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "I need legal assistance",
            contacts: [
              { id: "1", name: "Attorney", phoneNumber: "5551234567" },
            ],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
      
      fireEvent.press(getByText("Copy to Clipboard"));
      
      expect(mockSetString).toHaveBeenCalledWith(
        expect.stringMatching(/I'd like you to have a copy.*Message 1: Legal Support.*I need legal assistance.*Attorney - 5551234567/s)
      );
    });

    it("shows loading text while data is loading", () => {
      mockLoadEmergencyPlanData.mockImplementation(
        () => new Promise(resolve => setTimeout(resolve, 1000))
      );
      
      const { getByText } = render(<SecureCopy />);
      
      // Should show loading text in the plan area
      expect(getByText("Loading...")).toBeTruthy();
    });
  });

  describe("Navigation", () => {
    it("navigates to main screen when continue is pressed", async () => {
      const { getByTestId } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByTestId("button-continue")).toBeTruthy();
      });
      
      const continueButton = getByTestId("button-continue");
      fireEvent.press(continueButton);
      
      expect(mockReplace).toHaveBeenCalledWith("/main?planJustCompleted=true");
    });

    it("navigates to main screen when skip is pressed", async () => {
      const { getByTestId } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByTestId("button-skip")).toBeTruthy();
      });
      
      const skipButton = getByTestId("button-skip");
      fireEvent.press(skipButton);
      
      expect(mockReplace).toHaveBeenCalledWith("/main?planJustCompleted=true");
    });

    it("includes planJustCompleted parameter in navigation", async () => {
      const { getByTestId } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByTestId("button-continue")).toBeTruthy();
      });
      
      fireEvent.press(getByTestId("button-continue"));
      
      expect(mockReplace).toHaveBeenCalledWith(
        expect.stringContaining("planJustCompleted=true")
      );
    });
  });

  describe("Plan Text Formatting", () => {
    it("includes header with equals signs", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Other",
            message: "Test",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        const planText = getByText(/I'd like you to have a copy of my Emergency Plan/);
        expect(planText).toBeTruthy();
      });
    });

    it("numbers messages sequentially", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          { id: "1", topic: "Legal Support", message: "Message 1", contacts: [] },
          { id: "2", topic: "Pet Care", message: "Message 2", contacts: [] },
          { id: "3", topic: "Other", message: "Message 3", contacts: [] },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/Message 1: Legal Support/)).toBeTruthy();
        expect(getByText(/Message 2: Pet Care/)).toBeTruthy();
        expect(getByText(/Message 3: Other/)).toBeTruthy();
      });
    });

    it("numbers contacts sequentially within each message", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "Test",
            contacts: [
              { id: "1", name: "Contact 1", phoneNumber: "1111111111" },
              { id: "2", name: "Contact 2", phoneNumber: "2222222222" },
              { id: "3", name: "Contact 3", phoneNumber: "3333333333" },
            ],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/1\. Contact 1 - 1111111111/)).toBeTruthy();
        expect(getByText(/2\. Contact 2 - 2222222222/)).toBeTruthy();
        expect(getByText(/3\. Contact 3 - 3333333333/)).toBeTruthy();
      });
    });
  });

  describe("Edge Cases", () => {
    it("handles messages with no contacts", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Other",
            message: "Message with no contacts",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/No contacts added/)).toBeTruthy();
      });
    });

    it("handles undefined contacts array", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Other",
            message: "Test",
            contacts: undefined as any,
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/No contacts added/)).toBeTruthy();
      });
    });

    it("handles null messages", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: null as any,
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("No emergency plan data found.")).toBeTruthy();
      });
    });

    it("handles undefined messages", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: undefined as any,
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("No emergency plan data found.")).toBeTruthy();
      });
    });
  });

  describe("Multiple Messages", () => {
    it("formats multiple messages with different topics", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Child / Family Care",
            message: "Please pick up kids from school",
            contacts: [
              { id: "1", name: "School", phoneNumber: "5551111111" },
            ],
          },
          {
            id: "2",
            topic: "Work Absences",
            message: "Cannot come to work",
            contacts: [
              { id: "1", name: "Boss", phoneNumber: "5552222222" },
            ],
          },
          {
            id: "3",
            topic: "Pet Care",
            message: "Feed my cat",
            contacts: [
              { id: "1", name: "Neighbor", phoneNumber: "5553333333" },
            ],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText(/Message 1: Child \/ Family Care/)).toBeTruthy();
        expect(getByText(/Message 2: Work Absences/)).toBeTruthy();
        expect(getByText(/Message 3: Pet Care/)).toBeTruthy();
      });
    });
  });

  describe("Copy Multiple Times", () => {
    it("allows copying multiple times", async () => {
      mockLoadEmergencyPlanData.mockResolvedValue({
        messages: [
          {
            id: "1",
            topic: "Legal Support",
            message: "Test",
            contacts: [],
          },
        ],
      });
      
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
      
      const copyButton = getByText("Copy to Clipboard");
      
      // First copy
      fireEvent.press(copyButton);
      expect(mockSetString).toHaveBeenCalledTimes(1);
      
      // Wait for copied state to reset
      act(() => {
        jest.advanceTimersByTime(3000);
      });
      
      await waitFor(() => {
        expect(getByText("Copy to Clipboard")).toBeTruthy();
      });
      
      // Second copy
      fireEvent.press(copyButton);
      expect(mockSetString).toHaveBeenCalledTimes(2);
    });
  });

  describe("UI Elements", () => {
    it("renders bottom navigation", async () => {
      const { getByTestId } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByTestId("bottom-navigation")).toBeTruthy();
      });
    });

    it("displays recommendation text", async () => {
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("We recommend saving a copy of your emergency plan in a secure location.")).toBeTruthy();
      });
    });

    it("displays share instructions", async () => {
      const { getByText } = render(<SecureCopy />);
      
      await waitFor(() => {
        expect(getByText("You can share this with trusted contacts or save it for your records.")).toBeTruthy();
      });
    });
  });
});

